import { EnvironmentId } from '@/domains/environments';
import axios, { parseAxiosError } from '@/portainer/services/axios/axios';
import { ImageId, ImageName } from '@/domains/images/models/image';
import { buildDockerProxyUrl } from '@/providers/infrastructure/docker';

import { withAgentTargetHeader } from '../utils';

/**
 * Raw docker API proxy
 * @param environmentId
 * @param id
 * @param repo string generated by `buildImageFullURIFromModel` or `buildImageFullURI`
 * @returns
 */
export async function tagImage(
  environmentId: EnvironmentId,
  id: ImageId | ImageName,
  repo: string,
  tag?: string,
  { nodeName }: { nodeName?: string } = {}
) {
  try {
    const { data } = await axios.post(
      buildDockerProxyUrl(environmentId, 'images', id, 'tag'),
      {},
      {
        params: { repo, tag },
        headers: { ...withAgentTargetHeader(nodeName) },
      }
    );
    return data;
  } catch (e) {
    throw parseAxiosError(e, 'Unable to tag image');
  }
}
