import { TeamId } from '@/domains/teams';
import { UserId } from '@/domains/users';

import {
  AccessControlFormData,
  OwnershipParameters,
  ResourceControlOwnership,
  ResourceAccessLevel,
  ResourceId,
  isReadWriteResourceAccess,
} from './types';
import { ResourceControlViewModel } from './models/ResourceControlViewModel';

/**
 * Transform AccessControlFormData to ResourceControlOwnershipParameters
 * @param {int} userId ID of user performing the operation
 * @param {AccessControlFormData} formValues Form data (generated by AccessControlForm)
 * @param {int[]} subResources Sub Resources restricted by the ResourceControl
 */
export function parseOwnershipParameters(
  formValues: AccessControlFormData,
  subResourcesIds: ResourceId[] = []
): OwnershipParameters {
  const {
    ownership,
    authorizedTeams,
    authorizedUsers,
    readOnlyAuthorizedTeams = [],
    readOnlyAuthorizedUsers = [],
  } = formValues;

  const adminOnly = ownership === ResourceControlOwnership.ADMINISTRATORS;
  const publicOnly = ownership === ResourceControlOwnership.PUBLIC;

  let users = authorizedUsers;
  let teams = authorizedTeams;
  let readOnlyUsers = readOnlyAuthorizedUsers;
  let readOnlyTeams = readOnlyAuthorizedTeams;
  if (
    [
      ResourceControlOwnership.ADMINISTRATORS,
      ResourceControlOwnership.PUBLIC,
    ].includes(ownership)
  ) {
    users = [];
    teams = [];
    readOnlyUsers = [];
    readOnlyTeams = [];
  }

  return {
    administratorsOnly: adminOnly,
    public: publicOnly,
    users,
    teams,
    readOnlyUsers,
    readOnlyTeams,
    subResourcesIds,
  };
}

export function defaultValues(
  isAdmin: boolean,
  currentUserId: UserId
): AccessControlFormData {
  if (!isAdmin) {
    return {
      ownership: ResourceControlOwnership.PRIVATE,
      authorizedTeams: [],
      authorizedUsers: [currentUserId],
      readOnlyAuthorizedTeams: [],
      readOnlyAuthorizedUsers: [],
    };
  }

  return {
    ownership: ResourceControlOwnership.ADMINISTRATORS,
    authorizedTeams: [],
    authorizedUsers: [],
    readOnlyAuthorizedTeams: [],
    readOnlyAuthorizedUsers: [],
  };
}

export function parseAccessControlFormData(
  isAdmin: boolean,
  currentUserId: UserId,
  resourceControl?: ResourceControlViewModel
): AccessControlFormData {
  if (!resourceControl) {
    return defaultValues(isAdmin, currentUserId);
  }

  let ownership = resourceControl.Ownership;
  if (isAdmin && ownership === ResourceControlOwnership.PRIVATE) {
    ownership = ResourceControlOwnership.RESTRICTED;
  }

  let authorizedTeams: TeamId[] = [];
  let authorizedUsers: UserId[] = [];
  let readOnlyAuthorizedTeams: TeamId[] = [];
  let readOnlyAuthorizedUsers: UserId[] = [];
  if (
    [
      ResourceControlOwnership.PRIVATE,
      ResourceControlOwnership.RESTRICTED,
    ].includes(ownership)
  ) {
    authorizedTeams = resourceControl.TeamAccesses.filter((ra) =>
      isReadWriteResourceAccess(ra.AccessLevel)
    ).map((ra) => ra.TeamId);
    authorizedUsers = resourceControl.UserAccesses.filter((ra) =>
      isReadWriteResourceAccess(ra.AccessLevel)
    ).map((ra) => ra.UserId);
    readOnlyAuthorizedTeams = resourceControl.TeamAccesses.filter(
      (ra) => ra.AccessLevel === ResourceAccessLevel.ReadOnlyAccessLevel
    ).map((ra) => ra.TeamId);
    readOnlyAuthorizedUsers = resourceControl.UserAccesses.filter(
      (ra) => ra.AccessLevel === ResourceAccessLevel.ReadOnlyAccessLevel
    ).map((ra) => ra.UserId);
  }

  return {
    ownership,
    authorizedUsers,
    authorizedTeams,
    readOnlyAuthorizedUsers,
    readOnlyAuthorizedTeams,
  };
}
